server:
  port: 9000

spring:
  application:
    name: authservice
#  cloud:
#    config:
#      enabled: true
    jpa:
      hibernate:
        ddl-auto: create

    datasource:
      url: jdbc:sqlserver://sop2020-auth.database.windows.net:1433;database=sop202-auth-db
      username: gottemdd@sop2020-auth
      password: P@ssw0rd
    # encrypt=: true
    # trustServerCertificate: false
    # hostNameInCertificate: *.database.windows.net;loginTimeout=30

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fatchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
        
        
        
        
        
        
        