server:
  port: 9000

spring:
  application:
    name: authservice
#  cloud:
#    config:
#      enabled: true

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fatchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
        
        
        
        
        
        
        