server:
  port: 9000

spring:
  application:
    name: authservice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:sqlserver://sop2020-auth.database.windows.net:1433;database=sop202-auth-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: gottemdd@sop2020-auth
    password: P@ssw0rd
    initialization-mode: always
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
