server:
  port: 9000

spring:
  application:
    name: authservice
#    jpa:
#      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
##        ddl-auto: create
#      properties:
#        hibernate:
#          show_sql: true
#          format_sql: true
#    datasource:
#      url: jdbc:sqlserver://sop2020-auth.database.windows.net:1433;database=sop202-auth-db
#      username: gottemdd@sop2020-auth
#      password: P@ssw0rd
#      driver-class-name: com.mysql.jdbc.Driver
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
